pub mod calendar;
pub mod mfa;
#[cfg(feature = "stickers")]
pub mod stickers;
pub mod contact_groups;
pub mod contacts;
pub mod display_preferences;
pub mod drafts;
pub mod filters;
pub mod folders;
pub mod identities;
pub mod messages;
pub mod notification_preferences;
pub mod pgp;
pub mod pool;
pub mod tags;
pub mod vacation;
